name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Linting
        run: |
          npm run lint
      - name: Coverage
        run: |
          npm run coverage
